# Part (1)- data imputation 

## upload matlab's data

In [ ]:
from scipy.io import loadmat
import numpy as np
import pandas as pd

In [ ]:
annots = loadmat('cars_train_annos.mat')

## Check verious methods for data imputation

In [ ]:
# https://towardsdatascience.com/facing-the-arima-model-against-neural-networks-745ba5a933ca

Originally, I tried to write a script that extracts all PM2.5 data available from environmental protection of Israel. But then I used Yuval's data from matlab (above). 

In [ ]:
# Arima models Vs. ML:
# https://towardsdatascience.com/facing-the-arima-model-against-neural-networks-745ba5a933ca

# time-series analysis in plurasight:

# FA and PCA in plurasight:
# https://app.pluralsight.com/course-player?clipId=9306a799-e3f5-41bc-bb65-474dafec524d
    
# FA in python:
# https://www.datacamp.com/community/tutorials/introduction-factor-analysis
# from factor_analyzer import FactorAnalyzer
# https://scikit-learn.org/stable/modules/generated/sklearn.decomposition.FactorAnalysis.html#sklearn.decomposition.FactorAnalysis
# blind source seperation? if non-Gaussian priors on the latent variables are assumed.
# https://scikit-learn.org/stable/auto_examples/decomposition/plot_ica_blind_source_separation.html#sphx-glr-auto-examples-decomposition-plot-ica-blind-source-separation-py
# https://scikit-learn.org/stable/modules/decomposition.html

# technically when we say FA we mean varimax-rotated principal component analysis

In [3]:
import numpy as np
import pandas as pd

In [20]:
# X = np.random.rand(10,5)

In [29]:
# X

In [74]:
G = np.random.rand(10,3)

In [75]:
F = np.random.rand(3,5)

In [76]:
G

array([[0.39887499, 0.25868312, 0.79348595],
       [0.5840844 , 0.87063411, 0.84165557],
       [0.16245394, 0.35716553, 0.28596862],
       [0.74534349, 0.22252331, 0.75446334],
       [0.65277712, 0.96770442, 0.30318783],
       [0.11232998, 0.41472656, 0.91533984],
       [0.74274971, 0.86629095, 0.44709888],
       [0.61750942, 0.64176317, 0.48511266],
       [0.7446682 , 0.50462566, 0.17565843],
       [0.22539797, 0.72084979, 0.73391664]])

In [77]:
F

array([[0.95959013, 0.22197795, 0.39603034, 0.95842235, 0.04710638],
       [0.28557944, 0.2614658 , 0.36862438, 0.17232797, 0.93638644],
       [0.18525169, 0.50439401, 0.00849516, 0.39499191, 0.72722094]])

In [78]:
X = np.matmul(G,F)
X

array([[0.6036257 , 0.5564078 , 0.26006429, 0.74028957, 0.83805652],
       [0.96503495, 0.78182093, 0.5594021 , 1.04228129, 1.45483363],
       [0.3108645 , 0.27368862, 0.19842596, 0.33020439, 0.55005994],
       [0.91853795, 0.60417885, 0.38361544, 1.05070776, 0.79213978],
       [0.95892103, 0.55084986, 0.61781462, 0.91215546, 1.15737979],
       [0.39579637, 0.59506353, 0.20514036, 0.54068038, 1.05929008],
       [1.042956  , 0.61689351, 0.61728556, 1.03775452, 1.17131101],
       [0.86569825, 0.54956051, 0.48524313, 0.89404414, 0.98281104],
       [0.89122799, 0.38584333, 0.48242077, 0.87005142, 0.63534574],
       [0.55810885, 0.6086941 , 0.36122198, 0.63014016, 1.21933119]])

In [79]:
np.reshape(G[:,2],(-1,1)).shape

(10, 1)

In [80]:
np.reshape(F[2,:],(1,-1)).shape

(1, 5)

In [81]:
# G1*F1 
# X matrix related to factor1
np.matmul(np.reshape(G[:,0],(-1,1)),np.reshape(F[0,:],(1,-1)))

array([[0.38275651, 0.08854145, 0.1579666 , 0.38229071, 0.01878956],
       [0.56048163, 0.12965386, 0.23131514, 0.55979955, 0.0275141 ],
       [0.1558892 , 0.03606119, 0.06433669, 0.15569949, 0.00765262],
       [0.71522426, 0.16544982, 0.29517863, 0.71435386, 0.03511043],
       [0.62639848, 0.14490213, 0.25851954, 0.62563619, 0.03074997],
       [0.10779074, 0.02493478, 0.04448608, 0.10765956, 0.00529146],
       [0.71273529, 0.16487406, 0.29415142, 0.71186792, 0.03498825],
       [0.59255594, 0.13707347, 0.24455246, 0.59183483, 0.02908863],
       [0.71457626, 0.16529992, 0.2949112 , 0.71370665, 0.03507862],
       [0.21628967, 0.05003338, 0.08926443, 0.21602645, 0.01061768]])

In [82]:
# G2*F2
# X matrix related to factor2
np.matmul(np.reshape(G[:,1],(-1,1)),np.reshape(F[1,:],(1,-1)))

array([[0.07387458, 0.06763679, 0.09535691, 0.04457834, 0.24222737],
       [0.2486352 , 0.22764104, 0.32093696, 0.1500346 , 0.81524997],
       [0.10199913, 0.09338657, 0.13165992, 0.06154961, 0.33444496],
       [0.06354808, 0.05818224, 0.08202752, 0.03834699, 0.20836781],
       [0.27635649, 0.25302161, 0.35671944, 0.16676253, 0.90614529],
       [0.11843738, 0.10843681, 0.15287832, 0.07146898, 0.38834433],
       [0.24739488, 0.22650546, 0.31933597, 0.14928616, 0.8111831 ],
       [0.18327437, 0.16779912, 0.23656955, 0.11059374, 0.60093833],
       [0.14411071, 0.13194235, 0.18601732, 0.08696111, 0.47252462],
       [0.20585988, 0.18847757, 0.26572281, 0.12422258, 0.67499396]])

In [83]:
# G3*F3
# X matrix related to factor3
np.matmul(np.reshape(G[:,2],(-1,1)),np.reshape(F[2,:],(1,-1)))

array([[0.14699461, 0.40022956, 0.00674079, 0.31342053, 0.57703959],
       [0.15591812, 0.42452603, 0.00715   , 0.33244714, 0.61206955],
       [0.05297617, 0.14424086, 0.00242935, 0.11295529, 0.20796237],
       [0.13976561, 0.38054679, 0.00640929, 0.29800691, 0.54866154],
       [0.05616606, 0.15292612, 0.00257563, 0.11975674, 0.22048453],
       [0.16956825, 0.46169194, 0.00777596, 0.36155183, 0.6656543 ],
       [0.08282582, 0.225514  , 0.00379818, 0.17660044, 0.32513966],
       [0.08986794, 0.24468792, 0.00412111, 0.19161557, 0.35278408],
       [0.03254102, 0.08860106, 0.00149225, 0.06938366, 0.12774249],
       [0.1359593 , 0.37018316, 0.00623474, 0.28989113, 0.53371954]])

In [ ]:
# change Q1

In [232]:
import operator as op
from functools import reduce

def nck(n, k):
    k = min(k, n-k)
    numer = reduce(op.mul, range(n, n-k, -1), 1)
    denom = reduce(op.mul, range(1, k+1), 1)
    return numer / denom

In [233]:
p = 0.8 #probability to ruin a toy
q = 1-p
n = 8 # number of toys each kid got
k = 6 #at least number of toys

In [234]:
no_toys_a_kid_ruins_a_day = 0
for i in range(k,n+1):
    no_toys_a_kid_ruins_a_day = no_toys_a_kid_ruins_a_day + nck(n,i)*(p**i)*(q**(n-i))

In [235]:
no_toys_a_kid_ruins_a_day

0.79691776

In [236]:
p1 = no_toys_a_kid_ruins_a_day
q1 = 1-p1
n1 = 11 # number of kids yudicolus have
k1 = 9 # at least number of kids

In [237]:
no_kids = 0
for i in range(k1,n1+1):
    no_kids = no_kids + nck(n1,i)*(p1**i)*(q1**(n1-i))

In [238]:
no_kids

0.607163697719032

In [ ]:
# change Q2

In [241]:
balls=26
winning=11

p = winning/balls
q=1-p
#a
n = 6
(1-p)**(n-1)*p #probability to only extract winning in the nth trial

0.027040137309141496

In [242]:
#b #E
1/p

2.3636363636363638

In [243]:
#b2 #Var
q/(p**2)

3.2231404958677685

In [244]:
until = 3
k = 10 

p*q**(until-1)

0.1408170232134729

In [245]:
# import datetime
# import numpy as np
# import pandas as pd

# import plotly.graph_objects as go
# from ipywidgets import widgets

In [248]:
# df = pd.read_csv('https://raw.githubusercontent.com/yankev/testing/master/datasets/nycflights.csv')
# df = df.drop(df.columns[[0]], axis=1)

In [255]:
# df = pd.DataFrame([[2013,9,19,1846.0,16.0,2250.0,np.NAN,'DL','N909DL',2391,'JFK','TPA',np.NAN],
#                    [2012,2,1,1146.0,0,1350.0,-11,'FL','N969AT',353,'LGA','CAK',65]],columns =
#                   ['year','month','day','dep_time','dep_delay','arr_time','arr_delay','carrier','tailnum',
#                    'flight','origin','dest','air_time'])

In [256]:
# df

year  month  day  dep_time  dep_delay  arr_time  arr_delay carrier tailnum  \
0  2013      9   19    1846.0       16.0    2250.0        NaN      DL  N909DL   
1  2012      2    1    1146.0        0.0    1350.0      -11.0      FL  N969AT   

   flight origin dest  air_time  
0    2391    JFK  TPA       NaN  
1     353    LGA  CAK      65.0

# Import

In [1]:
import requests
import pandas as pd
import numpy as np
import json
from pandas.io.json import json_normalize
from datetime import datetime, timedelta
from dateutil.relativedelta import relativedelta
from matplotlib import pyplot as plt
import matplotlib.cm as cm
import itertools
import metpy as mp
import metpy.calc as mpcalc
import plotly as py
import plotly.graph_objs as go
import plotly.figure_factory as ff
from scipy import special
import ipywidgets as widgets
from metpy.units import units


from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"
%config InlineBackend.figure_format = 'retina'

# Functions 

In [93]:
# extraction is in UTC time. it gives you results for UTC time. 
# the true corresponding time in Israel it was 2 or 3 hours later
def get_station_props():
    station_names = []
    station_ids = []
    station_latitude = []
    station_longitude = []
    myUrl = 'https://api.svivaaqm.net/v1/envista/stations/?from=2019-11-01T00:00&to=2019/11/01T00:30'
    head = {'Authorization': 'ApiToken {}'.format(myToken), 'envi-data-source': 'MANA'}
    response = requests.get(myUrl, headers=head)
    j_response = response.json()
    for row in j_response:
        station_ids.append(row['stationId'])
        station_names.append(row['name'])
        station_latitude.append(row['location']['latitude'])
        station_longitude.append(row['location']['longitude'])
    return station_ids,station_names,station_latitude,station_longitude

def get_data_by_stationId(from_date, to_date, stationId):
    myUrl = 'https://api.svivaaqm.net/v1/envista/stations/'+stationId+'/data?from='+from_date+'&to='+to_date
    head = {'Authorization': 'ApiToken {}'.format(myToken), 'envi-data-source': 'MANA'}
    response = requests.get(myUrl, headers=head)
    return response

# use this to get column names and units of the station
def get_column_names(stationId):
    myUrl = 'https://api.svivaaqm.net/v1/envista/stations/'+stationId+'?from=2019-12-01T00:00&to=2019/12/01T00:06'
    head = {'Authorization': 'ApiToken {}'.format(myToken), 'envi-data-source': 'MANA'}
    response = requests.get(myUrl, headers=head)
    # units
    extract = response.json()['monitors']
    units = dict()
    for e in extract:
        units.update({e['name']:e['units']})
    column_names = [i + ' [' + j +']' for i, j in units.items()]
    return list(units.keys()), column_names


def get_dataFrame(dict_train,stationId):
    dates = []
    for row in dict_train:
        dates.append(row['datetime'])

    pollutants = []
    for row in dict_train:
        pollutant = dict()
        for p in row['channels']:
            pollutant.update({p['name']:p['value']})
        pollutants.append(pollutant)

    cols, station_columns = get_column_names(str(stationId))

    total_list = []
    for c in cols: #number of columns(j)
        vals = []
        for p in pollutants: #number of rows or values(i)
            if p[c] is not None:
                vals.append(p[c])
            else:
                vals.append(np.NaN)
        total_list.append(vals)

    data_df = pd.DataFrame(np.transpose(total_list), index = pd.to_datetime(dates,utc=True).tz_convert('Israel'), columns = station_columns)
    
    return data_df

In [94]:
myToken = '71e67c41-8478-4310-9293-196f559493ca'

In [95]:
# get a list of station names, ids, latitude and longitude
station_ids,station_names,station_latitude, station_longitude = get_station_props()

In [ ]:
# constract a dataframe of station properties

In [101]:
prop_df = pd.DataFrame(np.transpose([station_ids,station_names,station_latitude,station_longitude]), columns = ['station_ids','station_names','station_latitude','station_longitude'])

In [102]:
df.set_index('month')

station_ids  station_names station_latitude station_longitude
0             1          עפולה          32.6033            35.291
1             2          עמיאל           32.047           34.7926
2             3          אריאל          32.1035           35.1678
3             5  בר אילן -י''ם          31.7945             35.22
4             6        באר שבע          31.2567           34.7813
..          ...            ...              ...               ...
153         465           אלעד          32.0593           34.9517
154         467       לב אשדוד          31.7969           34.6483
155         468        אביגדור           31.711            34.745
156         469        תימורים          31.7159           34.7552
157         472        נחשולים          32.6139           34.9182

[158 rows x 4 columns]

In [92]:
# extract all stations info for the last X time by days

In [53]:
# getting data of last x months or days (in LOCAL TIME (now) or UTC time (utcnow)) for a specific station
num_days = 30
to_time = pd.Timestamp.utcnow().to_pydatetime().strftime('%Y-%m-%dT%H:%M')
from_time = (pd.Timestamp.utcnow().to_pydatetime() - relativedelta(days=num_days)).strftime('%Y-%m-%dT%H:%M')

In [55]:
for SI in str(station_ids[0]):
    stationData = get_data_by_stationId(from_time, to_time,SI)

In [56]:
stationData

<Response [200]>

In [57]:
dict_train = stationData.json()['data']
df1 = get_dataFrame(dict_train,SI)

In [59]:
df1.tail()

SO2 [ppb]  No [ppb]  Nox [ppb]  No2 [ppb]  \
2020-04-21 10:55:00+03:00        1.6       2.4       13.8       11.4   
2020-04-21 11:00:00+03:00        1.4       1.9       11.5        9.6   
2020-04-21 11:05:00+03:00        1.3       2.4       13.3       10.9   
2020-04-21 11:10:00+03:00        1.4       2.2       11.5        9.4   
2020-04-21 11:15:00+03:00        1.4       1.6       10.8        8.9   

                           O3 [ppb]  PM10 [µg/m3]  WS [m/sec]  WD [deg]  \
2020-04-21 10:55:00+03:00      48.5          44.0         2.4     157.0   
2020-04-21 11:00:00+03:00      48.3          44.0         2.3     120.0   
2020-04-21 11:05:00+03:00      46.9          44.0         1.9     134.0   
2020-04-21 11:10:00+03:00      48.9          44.0         2.7     134.0   
2020-04-21 11:15:00+03:00      47.3          44.0         2.5     139.0   

                           Temp [°c]  RH [%]  GSR [w/m2]  StWd [deg]  \
2020-04-21 10:55:00+03:00       26.0    52.0       974.5        18.6   
2020-04-21 11:00:00+03:00       26.0    52.0       964.5        16.9   
2020-04-21 11:05:00+03:00       26.3    53.0       961.8        22.4   
2020-04-21 11:10:00+03:00       26.2    52.0       921.3        13.6   
2020-04-21 11:15:00+03:00       26.0    54.0       897.3        12.9   

                           PM2.5 [µg/m3]  
2020-04-21 10:55:00+03:00        -9999.0  
2020-04-21 11:00:00+03:00        -9999.0  
2020-04-21 11:05:00+03:00        -9999.0  
2020-04-21 11:10:00+03:00        -9999.0  
2020-04-21 11:15:00+03:00        -9999.0